name: Deploy client

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.6.2

jobs:
  deploy:
    runs-on: ubuntu-24.04

    container:
      image: barichello/godot-ci:4.6.2

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Godot export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          if [ -d /root/.config/godot ]; then
            mv /root/.config/godot ~/.config/godot
          fi
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable \
             ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Make build directory
        run: mkdir -p build/web

      - name: Export Web build
        run: godot --headless --verbose --export-release "Web" "build/web/index.html"

      - name: Install butler
        run: |
          apt-get update && apt-get install -y wget unzip
          wget -O butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Deploy to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push build/web ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME }}:html5
